### ISSUE TITLE
Issues with accepting hyperlinks

### ISSUE THREAD

**Issue by roboto84** [roboto84/arcadia_bot#1]
bot came up with the following message trying to add (https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fdialoguereview.com%2Fwp-content%2Fuploads%2F2017%2F06%2FScreen-Shot-2017-06-21-at-15.50.56.png):

`19-Feb-22 12:19:35] INFO [ClientNetwork] Received Message: {'id': 'roboto_api', 'username': 'panda80', 'profile': 'app', 'time': '02/19 12:19', 'category': 'chat_message', 'message': '/arc add https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fdialoguereview.com%2Fwp-content%2Fuploads%2F2017%2F06%2FScreen-Shot-2017-06-21-at-15.50.56.png ergonomics'}
[19-Feb-22 12:19:35] INFO [ClientNetwork] Sending: 181B (4.42% of buffer)
Traceback (most recent call last):
  File "/home/black/willow/arcadia_bot/arcadia_bot/arcadia_bot.py", line 89, in <module>
    arcadia_bot.run_bot()
  File "/home/black/willow/arcadia_bot/arcadia_bot/arcadia_bot.py", line 22, in run_bot
    self._socket_network.receive(self._receive_message_callback)
  File "/home/black/.cache/pypoetry/virtualenvs/arcadia-bot-t7FDTw63-py3.9/lib/python3.9/site-packages/wh00t_core/library/client_network.py", line 103, in receive
    comparator_result = call_back_comparator(package)
  File "/home/black/willow/arcadia_bot/arcadia_bot/arcadia_bot.py", line 33, in _receive_message_callback
    self._command_handler(command_term.strip())
  File "/home/black/willow/arcadia_bot/arcadia_bot/arcadia_bot.py", line 46, in _command_handler
    self._add_arc_data(arc_command_params)
  File "/home/black/willow/arcadia_bot/arcadia_bot/arcadia_bot.py", line 60, in _add_arc_data
    'tags': add_term[2].split(',')
IndexError: list index out of range
`

**Comment by roboto84** [comment]
Turns out to be a duplicate of #2, closing, as that issue was fixed. This issue was tested with that fix and worked correctly as well.
