### ISSUE TITLE
Issues with adding hyperlinks without command

### ISSUE THREAD

**Issue by roboto84** [roboto84/arcadia_bot#2]
Adding without "hyperlink command" cause the following array IndexError:

`[19-Feb-22 17:30:04] INFO [ClientNetwork] Received Message: {'id': 'roboto_api', 'username': 'guineaPig65', 'profile': 'app', 'time': '02/19 17:30', 'category': 'chat_message', 'message': '/arc add https://www.bleepingcomputer.com/news/security/protonmail-introduces-a-new-email-tracker-blocking-system/ fingerprinting,tracking,web'}
[19-Feb-22 17:30:04] INFO [ClientNetwork] Sending: 198B (4.83% of buffer)
Traceback (most recent call last):
  File "/home/black/willow/arcadia_bot/arcadia_bot/arcadia_bot.py", line 89, in <module>
    arcadia_bot.run_bot()
  File "/home/black/willow/arcadia_bot/arcadia_bot/arcadia_bot.py", line 22, in run_bot
    self._socket_network.receive(self._receive_message_callback)
  File "/home/black/.cache/pypoetry/virtualenvs/arcadia-bot-t7FDTw63-py3.9/lib/python3.9/site-packages/wh00t_core/library/client_network.py", line 103, in receive
    comparator_result = call_back_comparator(package)
  File "/home/black/willow/arcadia_bot/arcadia_bot/arcadia_bot.py", line 33, in _receive_message_callback
    self._command_handler(command_term.strip())
  File "/home/black/willow/arcadia_bot/arcadia_bot/arcadia_bot.py", line 46, in _command_handler
    self._add_arc_data(arc_command_params)
  File "/home/black/willow/arcadia_bot/arcadia_bot/arcadia_bot.py", line 60, in _add_arc_data
    'tags': add_term[2].split(',')
IndexError: list index out of range`

**Comment by roboto84** [comment]
This was fixed by [#e352b35](https://github.com/roboto84/arcadia_bot/commit/e352b35723aa965af57bef9dd311dc0c994de4ab)

**Comment by roboto84** [comment]
Closing issue
